-- FarmGuard Supabase schema
create table if not exists public.scans (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  disease_name text not null,
  confidence text,
  image_path text,
  created_at timestamptz default now()
);

alter table public.scans enable row level security;
create policy "Users can view own scans" on public.scans for select using (auth.uid() = user_id);
create policy "Users can insert own scans" on public.scans for insert with check (auth.uid() = user_id);
create policy "Users can delete own scans" on public.scans for delete using (auth.uid() = user_id);

insert into storage.buckets (id,name,public) values ('crop-images','crop-images',false)
on conflict (id) do nothing;

create policy "Users upload own crop images"
on storage.objects for insert to authenticated
with check (bucket_id='crop-images' and (storage.foldername(name))[1]=auth.uid()::text);

create policy "Users read own crop images"
on storage.objects for select to authenticated
using (bucket_id='crop-images' and (storage.foldername(name))[1]=auth.uid()::text);
