-- AgriCare AI complete Supabase schema
create table if not exists public.profiles(id uuid primary key references auth.users(id) on delete cascade,full_name text,language text default 'English',created_at timestamptz default now());
create table if not exists public.categories(id bigint generated by default as identity primary key,name text unique not null);
create table if not exists public.crops(id bigint generated by default as identity primary key,name text unique not null,season text,description text);
create table if not exists public.diseases(id bigint generated by default as identity primary key,name text unique not null,crop_id bigint references public.crops(id) on delete set null,risk text,signs text,care text);
create table if not exists public.products(id bigint generated by default as identity primary key,name text unique not null,category_id bigint references public.categories(id) on delete set null,product_type text,crop_tags text,price numeric(10,2) not null,old_price numeric(10,2),stock integer default 0,rating numeric(2,1) default 0,description text,benefits jsonb default '[]'::jsonb,usage_instructions text,safety_information text,created_at timestamptz default now());
create table if not exists public.scans(id bigint generated by default as identity primary key,user_id uuid not null references auth.users(id) on delete cascade,disease_id bigint references public.diseases(id) on delete set null,disease_name text not null,confidence text,image_path text,created_at timestamptz default now());
create table if not exists public.favorites(id bigint generated by default as identity primary key,user_id uuid not null references auth.users(id) on delete cascade,product_id bigint references public.products(id) on delete cascade,created_at timestamptz default now(),unique(user_id,product_id));
create table if not exists public.cart_items(id bigint generated by default as identity primary key,user_id uuid not null references auth.users(id) on delete cascade,product_id bigint references public.products(id) on delete cascade,quantity integer not null default 1,created_at timestamptz default now(),unique(user_id,product_id));
create table if not exists public.orders(id bigint generated by default as identity primary key,user_id uuid not null references auth.users(id) on delete cascade,status text not null default 'Placed',payment_method text,delivery_name text,delivery_phone text,delivery_address text,total_amount numeric(10,2),created_at timestamptz default now());
create table if not exists public.order_items(id bigint generated by default as identity primary key,order_id bigint not null references public.orders(id) on delete cascade,product_id bigint references public.products(id) on delete set null,product_name text,quantity integer not null,unit_price numeric(10,2) not null);
create table if not exists public.reviews(id bigint generated by default as identity primary key,user_id uuid not null references auth.users(id) on delete cascade,product_id bigint references public.products(id) on delete cascade,rating integer not null check(rating between 1 and 5),title text,review_text text not null,created_at timestamptz default now());
create table if not exists public.reminders(id bigint generated by default as identity primary key,user_id uuid not null references auth.users(id) on delete cascade,title text not null,reminder_date date,reminder_type text,created_at timestamptz default now());
create table if not exists public.addresses(id bigint generated by default as identity primary key,user_id uuid not null references auth.users(id) on delete cascade,label text,full_name text,phone text,address_text text,pin text,created_at timestamptz default now());

insert into public.categories(name) values('Bio-input'),('Fungicide'),('Pest control'),('Fertilizer'),('Crop care') on conflict(name) do nothing;
insert into public.crops(name,season,description) values
('Rice','Kharif/Rabi','Warm-season cereal crop requiring good water management.'),
('Tomato','Year-round','Vegetable crop commonly affected by fungal and viral diseases.'),
('Chilli','Kharif/Rabi','Spice crop needing regular pest and disease monitoring.'),
('Cotton','Kharif','Fiber crop requiring careful pest monitoring.'),
('Maize','Kharif/Rabi','Cereal crop suited to well-drained soil.'),
('Groundnut','Kharif/Rabi','Oilseed crop requiring balanced irrigation.'),
('Mango','Summer','Fruit crop needing seasonal pest and disease care.'),
('Banana','Year-round','Fruit crop requiring regular moisture and nutrition.')
on conflict(name) do nothing;

insert into public.diseases(name,crop_id,risk,signs,care)
select 'Rice Blast',id,'High','Spindle-shaped spots on leaves and neck lesions.','Remove severely affected material and follow local label guidance for an approved treatment.'
from public.crops where name='Rice' on conflict(name) do nothing;
insert into public.diseases(name,crop_id,risk,signs,care)
select 'Tomato Early Blight',id,'Moderate','Dark concentric leaf spots and yellowing.','Improve airflow, remove affected leaves and follow approved label directions.'
from public.crops where name='Tomato' on conflict(name) do nothing;
insert into public.diseases(name,crop_id,risk,signs,care)
select 'Chilli Leaf Curl',id,'High','Leaf curling, distortion and stunted growth.','Control vectors and follow local agricultural guidance.'
from public.crops where name='Chilli' on conflict(name) do nothing;
insert into public.diseases(name,crop_id,risk,signs,care)
select 'Cotton Bollworm',id,'High','Damaged squares and bolls with feeding holes.','Monitor regularly and use only locally approved products according to label instructions.'
from public.crops where name='Cotton' on conflict(name) do nothing;

alter table public.profiles enable row level security;
alter table public.scans enable row level security;
alter table public.favorites enable row level security;
alter table public.cart_items enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.reviews enable row level security;
alter table public.reminders enable row level security;
alter table public.addresses enable row level security;
alter table public.categories enable row level security;
alter table public.crops enable row level security;
alter table public.diseases enable row level security;
alter table public.products enable row level security;

drop policy if exists catalog_public_select on public.categories;
create policy catalog_public_select on public.categories for select using(true);
drop policy if exists crops_public_select on public.crops;
create policy crops_public_select on public.crops for select using(true);
drop policy if exists diseases_public_select on public.diseases;
create policy diseases_public_select on public.diseases for select using(true);
drop policy if exists products_public_select on public.products;
create policy products_public_select on public.products for select using(true);

drop policy if exists profile_select on public.profiles; create policy profile_select on public.profiles for select using(auth.uid()=id);
drop policy if exists profile_insert on public.profiles; create policy profile_insert on public.profiles for insert with check(auth.uid()=id);
drop policy if exists profile_update on public.profiles; create policy profile_update on public.profiles for update using(auth.uid()=id);
drop policy if exists scan_select on public.scans; create policy scan_select on public.scans for select using(auth.uid()=user_id);
drop policy if exists scan_insert on public.scans; create policy scan_insert on public.scans for insert with check(auth.uid()=user_id);
drop policy if exists scan_delete on public.scans; create policy scan_delete on public.scans for delete using(auth.uid()=user_id);
drop policy if exists fav_all on public.favorites; create policy fav_all on public.favorites for all using(auth.uid()=user_id) with check(auth.uid()=user_id);
drop policy if exists cart_all on public.cart_items; create policy cart_all on public.cart_items for all using(auth.uid()=user_id) with check(auth.uid()=user_id);
drop policy if exists order_select on public.orders; create policy order_select on public.orders for select using(auth.uid()=user_id);
drop policy if exists order_insert on public.orders; create policy order_insert on public.orders for insert with check(auth.uid()=user_id);
drop policy if exists order_update on public.orders; create policy order_update on public.orders for update using(auth.uid()=user_id) with check(auth.uid()=user_id);
drop policy if exists order_item_select on public.order_items; create policy order_item_select on public.order_items for select using(exists(select 1 from public.orders o where o.id=order_id and o.user_id=auth.uid()));
drop policy if exists order_item_insert on public.order_items; create policy order_item_insert on public.order_items for insert with check(exists(select 1 from public.orders o where o.id=order_id and o.user_id=auth.uid()));
drop policy if exists review_select on public.reviews; create policy review_select on public.reviews for select using(true);
drop policy if exists review_insert on public.reviews; create policy review_insert on public.reviews for insert with check(auth.uid()=user_id);
drop policy if exists review_update on public.reviews; create policy review_update on public.reviews for update using(auth.uid()=user_id);
drop policy if exists review_delete on public.reviews; create policy review_delete on public.reviews for delete using(auth.uid()=user_id);
drop policy if exists reminder_all on public.reminders; create policy reminder_all on public.reminders for all using(auth.uid()=user_id) with check(auth.uid()=user_id);
drop policy if exists address_all on public.addresses; create policy address_all on public.addresses for all using(auth.uid()=user_id) with check(auth.uid()=user_id);

insert into storage.buckets(id,name,public) values('crop-images','crop-images',false) on conflict(id) do nothing;
drop policy if exists crop_upload on storage.objects; create policy crop_upload on storage.objects for insert to authenticated with check(bucket_id='crop-images' and (storage.foldername(name))[1]=auth.uid()::text);
drop policy if exists crop_read on storage.objects; create policy crop_read on storage.objects for select to authenticated using(bucket_id='crop-images' and (storage.foldername(name))[1]=auth.uid()::text);
drop policy if exists crop_delete on storage.objects; create policy crop_delete on storage.objects for delete to authenticated using(bucket_id='crop-images' and (storage.foldername(name))[1]=auth.uid()::text);

create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.profiles(id,full_name) values(new.id,new.raw_user_meta_data->>'full_name') on conflict(id) do nothing; return new; end; $$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
